name: CI
on: [push, pull_request]

jobs:
  vader-tests:
    name: Vader tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [true] # only test on neovim currently
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: vader.vim
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
      - name: Run vader tests
        env:
          VIM_EXEC: ${{ steps.vim.outputs.executable }}
        run: |
          $VIM_EXEC --version
          $VIM_EXEC -u test/vimrc -c 'Vader! test/*'

  vint:
    name: Run vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint --warning --verbose --enable-neovim --color --style ./autoload ./plugin ./syntax

  translator-script:
    name: Test translator.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v1
      - name: Install translate-shell
        run: |
          sudo add-apt-repository ppa:schot/gawk -y
          sudo apt-get update -q
          sudo apt-get install gawk
          wget git.io/trans
          chmod +x ./trans
          export PATH=$PWD:$PATH
          echo $PATH
      - name: Run translator tests
        run: |
          python --version
          python ./test/test_translator.py
